### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by joelpittet** [d10/reveal-code-focus#4]
This may be obvious but how do you add this to reveal? Anything special needed for the dependencies?  May be nice to add to the README.md

**Comment by Delapouite** [comment]
Hi Joel.

Yes you need to add the script to the dependencies list. Something roughly like that : 
```
Reveal.initialize({
   // …
    dependencies: [
        { src: 'node_modules/reveal-code-focus/code-focus.js', async: true, callback: RevealCodeFocus }
 // …
});

**Comment by joelpittet** [comment]
Oh I was close I had this.
```
{ src: 'plugin/reveal-code-focus/code-focus.js',
	async: true,
	condition: function() { return !!document.querySelector( 'pre code' ); },
	callback: RevealCodeFocus
},
```

Which kinda worked.  Worth adding to the readme?

**Comment by d10** [comment]
Yeah, I've been kinda busy lately. Will try to add it in ASAP.

**Comment by nemoDreamer** [comment]
`callback: RevealCodeFocus` fails as it's not loaded yet, and should be `callback: function() { return RevealCodeFocus; }` or similar?

**Comment by joelpittet** [comment]
I think your correct there @nemoDreamer

**Comment by d10** [comment]
I’ve added [a Reveal.js slideshow](https://d10.github.io/reveal-code-focus) with instructions.

**Comment by nemoDreamer** [comment]
Brilliant, @d10 !

Linking to the `highlight.js` and not the plug-in is key, since otherwise, all code blocks' added style markup gets escaped and displayed... I finally gave up for the presentation I needed to give, but now that I've got the trick, I'll definitely give reveal another go!!
